name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    branches: [main, master]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    strategy:
      matrix:
        service: [product-service, order-service, customer-service, api-gateway]
        include:
          - service: product-service
            port: 3001
          - service: order-service
            port: 3002
          - service: customer-service
            port: 3003
          - service: api-gateway
            port: 3000
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            SERVICE=${{ matrix.service }}
            PORT=${{ matrix.port }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Bạn có thể thêm các bước triển khai tại đây, ví dụ:
      # - Triển khai lên Kubernetes
      # - Triển khai lên AWS ECS
      # - Triển khai lên VPS sử dụng SSH
      
      - name: Deploy notification
        run: echo "Deployment completed successfully!"
