name: Continuous Integration

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        service: [product-service, order-service, customer-service, api-gateway]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ${{ matrix.service }}/package-lock.json
      
      - name: Install dependencies
        working-directory: ${{ matrix.service }}
        run: npm ci
      
      - name: Lint
        working-directory: ${{ matrix.service }}
        run: npm run lint
      
      - name: Run tests
        working-directory: ${{ matrix.service }}
        run: npm test
      
      - name: Build
        working-directory: ${{ matrix.service }}
        run: npm run build
