name: Deploy Product Service to Render

on:
  push:
    branches: [ main, master ]
    paths:
      - 'product-service/**'
      - '.github/workflows/deploy-product-to-render.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.4.3
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          clear_cache: true
          wait_deploy: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
